FROM node:20-alpine as builder

WORKDIR /app
COPY apps/web/package*.json ./
RUN npm install

COPY apps/web/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
